### ISSUE TITLE
The demo app is in a broken state

### ISSUE THREAD

**Issue by tskogberg** [varvet/godmin#201]
The demo app that you link to in the readme is in a broken state.

**Comment by Linuus** [comment]
@tskogberg Thank you for the report!

@kindell Can you have a look at this if/when you have time?

**Comment by kindell** [comment]
I have no time and not enough mad skillz 😬  Latest commit by @jensljungblad, you know what might have happened?

**Comment by jensljungblad** [comment]
I think it may have something to do with Rails 5. But I won't have time to look at it for some time i think.

**Comment by Linuus** [comment]
I can fix it after the weekend 😊

Linus Pettersson

On fre 16 sep. 2016 at 08:24 Jens Ljungblad

<
mailto:Jens Ljungblad <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I think it may have something to do with Rails 5. But I won't have time to look at it for some time i think.

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/varvet/godmin/issues/201#issuecomment-247527170
, or

**Comment by Linuus** [comment]
Sorry I missed Jens comment.

**Comment by jensljungblad** [comment]
@Linuus did you have time to look at this? It's broken again!

**Comment by eahlberg** [comment]
It seems like the demo app has stopped working again.

**Comment by Linuus** [comment]
Yep. I thought I fixed it but it still breaks after the daily reset.

**Comment by Linuus** [comment]
I think I've solved this again... We'll know for sure after the next reset :)

What I did was to run: 
`heroku config:set DISABLE_DATABASE_ENVIRONMENT_CHECK=1`

To make Rails ignore that we're in a "production" env.

Closing this and we'll reopen if it breaks again.
