### ISSUE TITLE
Return 404 unless authenticated

### ISSUE THREAD

**Issue by jensljungblad** [varvet/godmin#25]
Consider failing with a 404 instead of 401 unless authenticated

**Comment by Linuus** [comment]
When not authenticated we return 302 and redirect to sign in. 404 and redirect is not possible. I don't think it really matters since we always return 302, regardless if the resource exists or not, we don't disclose any resource information.

If we want to be picky with the statuses, I think we should return 401 when not signed in (and not redirect, but render a sign in form), 404 if the resource is not found and 404 if the user does not have permission. That's probably the most correct behavior anyway :)

When not authorized we just raise `NotAuthorizedError` (?) and let the user rescue it and do whatever they want. Or am I wrong?

**Comment by jensljungblad** [comment]
Yup, we might wanna do something with that NotAuthorizedError. I believe we do that because that's how Pundit works. It's of course ok for Pundit not to care about what happens after that error is thrown, but since Godmin is an application we should probably handle it somehow. But wouldn't a 401 be the correct code when not authorized?

**Comment by Linuus** [comment]
It depends how careful you want to be. If you use 401 for unauthorized and 404 for not found you disclose information about the resources. You know there is a resource there because you get 401 and not 404. That's why Github returns 404 for private repos that you don't have access to, for instance.

**Comment by jensljungblad** [comment]
Well yeah, not sure 404 would be the "correct" code, but probably better from a security perspective :) I'm all for it! But doesn't the 401 when not signed in also disclose the same information?

**Comment by jensljungblad** [comment]
And that is probably the case we should worry about anyways, the not signed in one.

**Comment by Linuus** [comment]
No 401 when not signed in does not reveal anything. Not in our case anyway since we return it for everything, even pages that does not exist (which returns 404 when signed in).



If you don't care about leaking information then the correct thing, I think, is


- User not authenticated -> 401

- Page not found -> 404

- User authenticated but not correct permissions -> 403




However, 404 can be used instead of 403 if you don't want to disclose the information about the resource (according to the specs). But it's probably weird to use 404 instead of 403 all the time so maybe it's not a good default for an app like godmin :)

**Comment by jensljungblad** [comment]
Ah true. Yeah not sure it's super important to hide information from already authenticated users. Although those guys from the lokalavdelningar are not to be trusted.

**Comment by Linuus** [comment]
Haha yes but then we should return `403 Forbidden` I guess.
