### ISSUE TITLE
Don't add namespace twice

### ISSUE THREAD

**Issue by mwq** [varvet/godmin#87]
The PolicyFinder adds the namespace twice if Godmin is namespaced under "Admin" and a model is namespaced under the same namespace (Admin::Foo).

The obvious example:
     PolicyFinder.find(Admin::Foo) => Admin::Admin::Foo

If ruby does it's magic it also lead to: 
      PolicyFinder.find(Foo) => Admin::Admin::Foo

**Comment by jensljungblad** [comment]
I think we should go with https://github.com/varvet/godmin/pull/92 for now, and hold off changing the actual policy finder. We need to think about if we want to diverge from how Pundit works. That could be a problem if we want to try and switch back to actually using Pundit.

**Comment by jensljungblad** [comment]
Merged #92 so now it's possible to override the policy class. We should think about if we still want to do this. If we do, we should probably fix this not only for policy classes but for service objects and models as well.

**Comment by anderscarling** [comment]
Maybe Policy lookup should be based on Service object name/namespace instead of model?

I kinda feel like the Policy is so tightly coupled to the service it would kinda make more sense. It would also make #122 a bit more straight forward.

**Comment by jensljungblad** [comment]
@anderscarling Hm, interesting idea. But that would probably mean we would need to change the authorization interface, which now mimics that of Pundit. Originally the plan was to use Pundit but we had to build our own policy lookup because the policies and the models can be in different namespaces, say an `Article` and an `Admin::ArticlePolicy`.

If I understand you correctly you would suggest passing both the service object and the model instance to `authorize`? And use the service object to look up the policy then pass the model instance when instantiating it.

Another approach that I've been thinking about is if we should just expect there to always be a namespaced model. So if you have an `Article` you would (if you have an admin engine) also have

```ruby
module Admin
  class Article < ::Article
  end
end
```

Kinda like Rails .keep folders. A best practice place to put model code that is specific to the admin section. It could be generated by the resource generator. The problem I have with it is that it will lead to a lot of files. But it would solve the lookup issues because the models and the policies would be nested under the same namespace. We could probably switch to using Pundit then as well.

**Comment by jensljungblad** [comment]
Discussion moved to https://github.com/varvet/godmin/issues/182
